### ISSUE TITLE
FSP To-Do List

### ISSUE THREAD

**Issue by mwmadsen67** [Clipsey/streamTv#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [ ] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments

---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments

**Comment by mwmadsen67** [comment]
Sample State:
- I like the idea of planning two example slices of state, although I'm not sure they will ultimately look so similar.
- Great formatting.

Schema:
- Formatting is good, except for capitalized table names.
- The user's table has an excessive amount of columns. I'm not convinced that you will need most of those, nor will have time to implement features using them. Also, things like `stream_title` and `stream_category` will most like belong to different tables, and don't need to be stored under users.
- Categories most likely won't need a picture column, as that will be handled by active storage.
- Everything else looks great.

**Comment by mwmadsen67** [comment]
Be sure to get that MVP List done shortly. Twitch is a difficult clone and the more planning done now will help a lot down the line.

**Comment by mwmadsen67** [comment]
Another note on the schema: You will probably need a database constraint on unique friends and followers. This is done when putting an index on one of the columns and adding a unique true on the pair of id's. For example: `add_index :friends, [:friend_one_id, :friend_two_id], unique: true`

**Comment by mwmadsen67** [comment]
MVP List: 
- Looks great. No changes necessary.

Backend Routes: 
- For updating users, the HTTP verb used is `PATCH` not update.
- Where are your backend routes for videos?
- channel followers should be nested under users
- category followers should be nested under categories

Frontend Routes:
- Looks good. I'm wondering where videos are going and if you're still planning on having them. If you're just hosting streams from twitch's API I realize it won't utilize your videos from your DB, but right now I can't see anything that looks to be related to the videos table in your DB.

**Comment by Clipsey** [comment]
> MVP List:
> 
> * Looks great. No changes necessary.
> 
> Backend Routes:
> 
> * For updating users, the HTTP verb used is `PATCH` not update.
> * Where are your backend routes for videos?
> * channel followers should be nested under users
> * category followers should be nested under categories
> 
> Frontend Routes:
> 
> * Looks good. I'm wondering where videos are going and if you're still planning on having them. If you're just hosting streams from twitch's API I realize it won't utilize your videos from your DB, but right now I can't see anything that looks to be related to the videos table in your DB.

I don't plan to use Twitch for anything other than design right now. I set up a linux server, where I have live video streaming working, the user has to upload a stream through some software like OBS that has RTMP upload support, just like Twitch.tv has. My goal is to try to mimic close to what Twitch does, a user uploads a continuous video stream through OBS to a server, the RTMP stream is converted into a series of video fragment ".ts" files on the server, and then the browser fetches the .m3u8 file, from the server, that tells the browser what video fragment .ts files to grab at that time, and what to grab next.

The only real question I have there is how I'm going to "seed" the website with streams, I don't think I can just setup like 80 servers that continually stream to my one linux server taking RTMP streams. So I may have to embed either videos that start at random times, or use twitch video streams to for all the streams that I'm not streaming myself.

I had VODs, non-live video (still streaming), using S3 and cloudfront to test that I could read the video. I just got live streaming working this morning/last night, but yesterday I decided to make live chat the last "mandatory" feature and make VODs a bonus, because I thought that would be cooler to demo with a live stream. As a result, I didn't spend as much time designing how my backend will work with either VODs or chat, sorry about that, I think for chat it will use something like ActiveCable, some websocket connection thing I have to research. But until I have a better grasp of what's needed there, I won't be able to design the backend component for that, so far, I plan to have that done this weekend.

**Comment by mwmadsen67** [comment]
Cool, definitely sounds like you know what you're doing on the streaming front, but yes seeding will be the issue with this type of setup. Honestly, if you get streaming and chat working then that would be a great demo, and maybe you don't have to worry too much about having a whole bunch of streaming seeds. Just focus on the features you want to implement in the 2 weeks you have, and VODs can be something you come back to later.
